#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path

from .generate_preprocessor_sql import DEFAULT_PREPROCESSOR_LIBRARY_SCRIPT, ROOT, validate_identifier
from .preprocessor_library_builder import generate_preprocessor_library_body


DEFAULT_OUTPUT = ROOT / "dist" / "exasol-json-tables" / "json_preprocessor_library.sql"


def generate_preprocessor_library_sql_text(
    schema: str = "JVS_WRAP_PP",
    script: str = DEFAULT_PREPROCESSOR_LIBRARY_SCRIPT,
) -> str:
    validated_schema = validate_identifier("Schema", schema)
    validated_script = validate_identifier("Library script", script)
    body = generate_preprocessor_library_body(compact=True)
    return f"""-- Generated by tools/generate_preprocessor_library_sql.py
-- Shared JSON Tables preprocessor runtime library. Generated wrappers import this script with exa.import(...).

CREATE SCHEMA IF NOT EXISTS {validated_schema};

CREATE OR REPLACE SCRIPT {validated_schema}.{validated_script} AS
{body}/
"""


def install_preprocessor_library(
    con,
    schema: str = "JVS_WRAP_PP",
    script: str = DEFAULT_PREPROCESSOR_LIBRARY_SCRIPT,
) -> tuple[str, str]:
    validated_schema = validate_identifier("Schema", schema)
    validated_script = validate_identifier("Library script", script)
    con.execute(f"CREATE SCHEMA IF NOT EXISTS {validated_schema}")
    con.execute(
        f"CREATE OR REPLACE SCRIPT {validated_schema}.{validated_script} AS\n"
        + generate_preprocessor_library_body(compact=True)
        + "/"
    )
    return validated_schema, validated_script


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Generate installable Exasol SQL for the shared JSON Tables Lua preprocessor runtime library. "
            "Generated wrapper preprocessors import this library with exa.import(...)."
        )
    )
    parser.add_argument("--schema", default="JVS_WRAP_PP", help="Schema that will own the shared library script.")
    parser.add_argument(
        "--script",
        default=DEFAULT_PREPROCESSOR_LIBRARY_SCRIPT,
        help="Shared library script name.",
    )
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="Output SQL file.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    sql_text = generate_preprocessor_library_sql_text(args.schema, args.script)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(sql_text)
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
